# NOTEBOOK SETTINGS
[notebook]
dir = "~/notebook"

# NOTE SETTINGS
[note]

# Language used when writing notes.
# This is used to generate slugs or with date formats.
language = "en"

# The default title used for new note, if no `--title` flag is provided.
default-title = "Notes"

# Template used to generate a note's filename, without extension.
filename = "{{id}}-{{slug title}}"

# The file extension used for the notes.
extension = "md"

# Template used to generate a note's content.
# relative to .zk/templates/
template = "default.md"

# Configure random ID generation.

# The charset used for random IDs.
id-charset = "alphanum"

# Length of the generated IDs.
id-length = 4

# Letter case for the random IDs.
id-case = "lower"


# EXTRA VARIABLES
[extra]
author = "Grant"


# GROUP OVERRIDES
[group.journal]
paths = ["journal"]

[group.journal.note]
# %Y-%m-%d is actually the default format, so you could use {{format-date now}} instead.
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"


# MARKDOWN SETTINGS
[format.markdown]
# Format used to generate links between notes.
# Either "wiki", "markdown" or a custom template. Default is "markdown".
link-format = "wiki"
# Indicates whether a link's path will be percent-encoded.
link-encode-path = false
# Indicates whether a link's path file extension will be removed.
link-drop-extension = true


# EXTERNAL TOOLS
[tool]

# Default editor used to open notes.
editor = "nvim"

# Default shell used by aliases and commands.
shell = "/bin/zsh"

# Pager used to scroll through long output.
pager = "less -FIRX"

# Command used to preview a note during interactive fzf mode.
fzf-preview = "bat -p --color always {-1}"

# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two months'"

# COMMAND ALIASES
[alias]

# Go to index
i = "zk edit --limit 1 --match=index --tag=home"
# Show todays Jounral
today = 'zk new --no-input "$ZK_NOTEBOOK_DIR/journal"'
cd = 'cd $ZK_NOTEBOOK_DIR'
sync = "pushd $ZK_NOTEBOOK_DIR > /dev/null && git add . && (git diff-index --quiet HEAD || git commit -m \"Auto Sync $(date '+%Y-%m-%d %H:%M:%S')\") && popd > /dev/null && git push"
journal = 'zk edit journal --interactive'
conf = '$EDITOR "$HOME/.config/zk/config.toml"'
Configure = '$EDITOR "$HOME/.config/zk/config.toml"'
ls = "zk list $@"
ed = "zk edit $@"
review_chapter= 'book=$(zk list --tag "book" --format "{{title}}" --quiet | fzf) && read "input2?Enter chapter title: " && zk new --template chapter_review.md --title "${book} - ${input2} Review"'
n = 'read "title?Enter the title: " && zk new --title "$title"'

# LSP (EDITOR INTEGRATION)
[lsp]

[lsp.diagnostics]
# Report titles of wiki-links as hints.
wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"

[lsp.completion]
# Show the note title in the completion pop-up, or fallback on its path if empty.
note-label = "{{title-or-path}}"
# Filter out the completion pop-up using the note title or its path.
note-filter-text = "{{title}} {{path}}"
# Show the note filename without extension as detail.
note-detail = "{{filename-stem}}"
